### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by ClementEraud** [arthurlacoste/semantic-ui-offline#2]
Hello Arthur, 
Thank you for your project ! 
But I have one issue, is that when i try to 'npm start' my project with semantic-ui offline it throw me this error : 

ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/semantic-ui-offline/semantic.min.css
Module not found: Error: Can't resolve './fonts/lato-v14-latin-regular.eot' in 'C:\CCSP\ccsp-agent-front\node_modules\semantic-ui-offline' @ ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/semantic-ui-offline/semantic.min.css 6:331-376
 @ ./~/semantic-ui-offline/semantic.min.css @ multi ./~/semantic-ui-offline/semantic.min.css ./~/semantic-ui-calendar/dist/calendar.min.css ./~/semantic-ui-popup/popup.min.css ./src/styles.scsswebpack: Failed to compile.

It looks like he doesn't find semantic-ui-offline/fonts/v14-latin-regular.eot . Wich makes sense because there's only a folder semantic-ui-offline/font , btw it works when I change the semantic.min.css and change `src:url(fonts/lato-v14-latin-regular.eot)` for `src:url(font/lato-v14-latin-regular.eot)` . But It's not a suitable solution for me since I only use npm and not Gulp so I can't change the node-modules I install. 

Is it normal that you call `src:url(fonts/lato-v14-latin-regular.eot)` ?

**Comment by arthurlacoste** [comment]
Hi !

It's a mistake, I've updated the script & all files. 

Thank you for your issue 🍪 
Art'

**Comment by ClementEraud** [comment]
Great! Thanks for fixing so quickly ! 👍

**Comment by arthurlacoste** [comment]
Your welcome ;)

Arthur Lacoste
http://irz.fr
