### ISSUE TITLE
Release a version based on semantic-ui-css 2.3

### ISSUE THREAD

**Issue by ryanewtaylor** [arthurlacoste/semantic-ui-offline#4]
Would you have time to release a version of this based on semantic-ui-css 2.3.x?

**Comment by mjasnikovs** [comment]
As this repository seem to be abandoned, i created https://github.com/mjasnikovs/semantic-ui-css-offline
It will provide new version of CSS. Hope somebody else will find it useful. Semantic Ui version is 2.3.2

**Comment by arthurlacoste** [comment]
Done.

I've released too on NPM. 🚀
